name: biapay_app
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  email_validator: ^2.1.17
  auto_route: ^4.0.1
  cached_network_image: ^3.1.0
  country_code_picker: ^2.0.0
#  country_picker:


  dartz: ^0.10.0
  date_time_format: ^2.0.1
  desktop_window: ^0.4.0
  dotted_border: ^2.0.0+1
  excel: ^2.0.0-null-safety-3
  fl_chart: ^0.51.0
  flutter_echarts: ^2.3.0
  # flutter_hooks: ^0.18.0
  flutter_pdfview: ^1.2.1
  flutter_screenutil: ^5.0.0+2
  freezed_annotation: ^2.0.3
  geolocator: ^8.2.1
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  # hooks_riverpod: ^1.0.0-dev.11
  http: ^0.13.4
  image_picker: ^0.8.4+4
  json_annotation: ^4.3.0
  jwt_decoder: ^2.0.1
  local_auth: ^2.1.0
  logger: ^1.1.0
  open_file: ^3.2.1
  overlay_support: ^2.0.1
  path_provider: ^2.0.6
  pdf: ^3.8.1
  permission_handler: ^9.2.0
  persistent_bottom_nav_bar: ^4.0.2
  phone_form_field: ^5.0.3
  photo_view: ^0.14.0
  pinput: ^1.2.1
  searchfield: ^0.6.5
  syncfusion_flutter_datepicker: ^19.3.48
  video_player: ^2.2.6
  webview_flutter: ^2.8.0
  syncfusion_flutter_charts: ^19.1.48
  oktoast: ^3.1.5
  get_storage: ^2.0.3
  dio_logger: ^4.0.8+8
  auto_size_text: ^3.0.0
  pie_chart: ^5.3.2
  flutter_svg: ^1.0.3
  qr_code_scanner:
  dio: 4.0.6
  get: 4.6.5
  intl: 0.17.0
  carousel_slider: ^4.1.1
  encrypt: ^5.0.1
  flutter_rating_bar: ^4.0.1
  package_info_plus: ^1.4.2
  flutter_layout_grid: ^1.0.3
  intl_phone_field: ^3.1.0
  dropdown_below: ^1.0.3



#  carousel_slider:
#  mtn_orange_money: ^0.0.7
  clay_containers: ^0.3.2
  uuid:
  qr_flutter:
    git: https://github.com/theyakka/qr.flutter
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  auto_route_generator: ^4.0.0
  build_runner: ^2.1.4
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/data/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
